# Generated by Django 3.1.6 on 2021-02-20 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmed_Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_ID', models.IntegerField(unique=True)),
                ('Created_time', models.DateTimeField()),
                ('updated_time', models.DateField(default=datetime.date(2021, 2, 20))),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_ID', models.IntegerField(unique=True)),
                ('Subject', models.CharField(max_length=256)),
                ('Status', models.CharField(max_length=256)),
                ('Source', models.CharField(max_length=256)),
                ('Type', models.CharField(max_length=256)),
                ('Agent', models.CharField(max_length=256)),
                ('Group', models.CharField(max_length=256)),
                ('Created_time', models.DateTimeField()),
                ('Product', models.CharField(max_length=256)),
                ('Follow_up_Date', models.CharField(max_length=256, null=True)),
                ('Estimated_Delivery_Date', models.CharField(max_length=256, null=True)),
                ('Full_name', models.CharField(max_length=256)),
                ('Email', models.EmailField(max_length=256)),
                ('Company_Name', models.CharField(max_length=256)),
            ],
        ),
    ]
