# Generated by Django 3.1.6 on 2021-02-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Region',
        ),
    ]
