# Generated by Django 3.1.6 on 2021-02-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_ticket_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Created_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Ticket_ID',
            field=models.IntegerField(),
        ),
    ]
