# Generated by Django 3.1.6 on 2021-02-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210224_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmed_ticket',
            name='Ticket_ID',
            field=models.IntegerField(unique=True),
        ),
    ]
