# Generated by Django 3.1.6 on 2021-02-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20210211_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Estimated_Delivery_Date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Follow_up_Date',
        ),
    ]
