# Generated by Django 3.1.6 on 2021-02-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20210211_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Created_time',
        ),
    ]
