# Generated by Django 3.1.6 on 2021-02-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_remove_ticket_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Created_time',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='ticket',
            name='Estimated_Delivery_Date',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='ticket',
            name='Follow_up_Date',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
