# Generated by Django 3.1.6 on 2021-02-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20210211_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Ticket_ID',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
