# Generated by Django 3.1.6 on 2021-02-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_auto_20210212_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Created_time',
            field=models.DateTimeField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Estimated_Delivery_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Follow_up_Date',
            field=models.DateTimeField(),
        ),
    ]
