# Generated by Django 3.1.6 on 2021-02-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20210212_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Created_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Estimated_Delivery_Date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Follow_up_Date',
        ),
    ]
