# Generated by Django 3.1.6 on 2021-02-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_auto_20210212_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Created_time',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='ticket',
            name='Estimated_Delivery_Date',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='ticket',
            name='Follow_up_Date',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
