# Generated by Django 3.1.6 on 2021-02-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_auto_20210212_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Ticket_ID',
            field=models.CharField(max_length=256),
        ),
    ]
