# Generated by Django 3.1.6 on 2021-02-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_auto_20210212_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Created_time',
            field=models.DateTimeField(blank=True, max_length=256),
        ),
    ]
