# Generated by Django 3.1.6 on 2021-02-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_auto_20210212_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Estimated_Delivery_Date',
            field=models.DateTimeField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Follow_up_Date',
            field=models.DateTimeField(blank=True, max_length=256),
        ),
    ]
