# Generated by Django 3.1.6 on 2021-02-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_auto_20210212_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Created_time',
            field=models.DateField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Estimated_Delivery_Date',
            field=models.DateField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Follow_up_Date',
            field=models.DateField(blank=True, max_length=256),
        ),
    ]
