# Generated by Django 3.1.6 on 2021-02-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_auto_20210212_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Created_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Estimated_Delivery_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Follow_up_Date',
            field=models.DateField(),
        ),
    ]
