# Generated by Django 3.1.6 on 2021-02-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0023_auto_20210212_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Estimated_Delivery_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Follow_up_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
