# Generated by Django 3.1.6 on 2021-02-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0024_auto_20210212_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Ticket_ID',
            field=models.IntegerField(),
        ),
    ]
