# Generated by Django 3.1.6 on 2021-02-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0025_auto_20210212_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Created_time',
            field=models.DateTimeField(),
        ),
    ]
