# Generated by Django 3.1.6 on 2021-02-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0027_auto_20210212_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Created_time',
            field=models.DateTimeField(max_length=256),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Ticket_ID',
            field=models.IntegerField(),
        ),
    ]
