# Generated by Django 3.1.6 on 2021-02-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0028_auto_20210212_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Estimated_Delivery_Date',
            field=models.DateField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Follow_up_Date',
            field=models.DateField(max_length=256, null=True),
        ),
    ]
