# Generated by Django 3.1.6 on 2021-02-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0030_auto_20210212_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Created_time',
            field=models.CharField(max_length=256),
        ),
    ]
