# Generated by Django 3.1.6 on 2021-02-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0031_auto_20210212_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Ticket_ID',
            field=models.IntegerField(unique=True),
        ),
    ]
