# Generated by Django 3.1.6 on 2021-02-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0033_auto_20210213_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Created_time',
            field=models.DateTimeField(),
        ),
    ]
