# Generated by Django 3.1.6 on 2021-02-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0036_auto_20210213_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='updated_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
