# Generated by Django 3.1.6 on 2021-02-15 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0037_ticket_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='updated_Date',
        ),
    ]
