# Generated by Django 3.1.6 on 2021-02-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0038_remove_ticket_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmed_Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_ID', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
