# Generated by Django 3.1.6 on 2021-02-18 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0039_confirmed_ticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Confirmed_Ticket',
            new_name='MyModel',
        ),
    ]
