# Generated by Django 3.1.6 on 2021-02-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0040_auto_20210218_0818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
