# Generated by Django 3.1.6 on 2021-02-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0042_confirmed_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmed_ticket',
            name='Created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
