# Generated by Django 3.1.6 on 2021-02-18 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0043_auto_20210218_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmed_ticket',
            name='Created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
