# Generated by Django 3.1.6 on 2021-02-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0044_auto_20210218_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmed_ticket',
            name='Created_time',
            field=models.DateTimeField(),
        ),
    ]
