# Generated by Django 3.1.6 on 2021-02-18 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0046_auto_20210218_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_ticket',
            name='updated_time',
            field=models.DateField(default=datetime.date(2021, 2, 18)),
        ),
    ]
