# Generated by Django 3.1.6 on 2021-02-21 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_ticket',
            name='Subject',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AlterField(
            model_name='confirmed_ticket',
            name='updated_time',
            field=models.DateField(default=datetime.date(2021, 2, 21)),
        ),
    ]
