# Generated by Django 3.1.6 on 2021-02-24 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210221_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmed_ticket',
            name='Ticket_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.ticket'),
        ),
        migrations.AlterField(
            model_name='confirmed_ticket',
            name='updated_time',
            field=models.DateField(default=datetime.date(2021, 2, 24)),
        ),
    ]
