# Generated by Django 3.1.6 on 2021-02-27 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20210224_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmed_ticket',
            name='updated_time',
            field=models.DateField(default=datetime.date(2021, 2, 27)),
        ),
    ]
